name: aitapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  async: ^2.11.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_inappwebview: ^6.0.0
  flutter_localizations: 
  flutter_riverpod:
  fluttertoast: ^8.2.4
  hooks_riverpod: ^2.4.9
  http:
  intl: ^0.18.0
    sdk: flutter
  package_info: ^2.0.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  syncfusion_flutter_pdfviewer: ^24.1.41
  system_proxy: ^0.1.0
  universal_html:
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_launcher_icons:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true

  assets:
    - assets/pdfs/annual-events.pdf
    - assets/pdfs/binran_2023.pdf
    - assets/pdfs/guide-campus-yakusa.pdf
    - assets/html/index.html

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/0m030eac1c725117c9692003de113f170c70ea4d21ca66.png"