name: aitapp
description: L-cam flutter app

publish_to: 'none'

version: 1.6.1+9

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  async: ^2.11.0
  chewie: ^1.8.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_widget_from_html: ^0.15.0
  fluttertoast: ^8.2.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_drawing: ^1.0.1
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^25.2.6
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  webview_flutter: ^4.8.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.27.0

flutter:
  uses-material-design: true

  assets:
    - assets/pdfs/
    - assets/html/
    - assets/images/

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/0m030eac1c725117c9692003de113f170c70ea4d21ca66.png"