on:
  workflow_dispatch:
  push:
    branches:
    - release
jobs:
  build_app:
    name: Build app
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'
      - name: Create dot env file
        shell: bash
        run: |
          mkdir env
          cd env
          touch .env
          echo "BLOWFISHKEY=${{ secrets.BLOWFISH_KEY }}" >> .env
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get flutter Package
        run: flutter pub get
      - name: build_runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build app
        run: flutter build ios --release --no-codesign
      - name: Make ipa
        shell: bash
        run: |
          mkdir Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -ry Payload.zip Payload/Runner.app
          mv Payload.zip release.ipa
          rm -rf Payload
      - name: Upload artifact aab
        uses: actions/upload-artifact@v1.0.0
        with:
          name: release-ios
          path: ./release.ipa

          



