on:
  workflow_dispatch:
  push:
    branches:
    - release
jobs:
  build_app:
    name: Build app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Create dot env file
        shell: bash
        run: |
          mkdir env
          cd env
          touch .env
          echo "BLOWFISHKEY=${{ secrets.BLOWFISH_KEY }}" >> .env
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get flutter Package
        run: flutter pub get
      - name: build_runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build ipa
        run: flutter build ios --release --no-codesign
