on:
  workflow_dispatch:
  push:
    branches:
    - release
jobs:
  build_app:
    name: Build app
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Create dot env file
      - shell: bash
        run: |
          mkdir env
          cd env
          touch .env
          echo "BLOWFISHKEY=${{ secrets.BLOWFISH_KEY }}" >> .env
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
